#!/bin/bash
#PBS -q k40
#PBS -l nodes=1:ppn=20
#PBS -l walltime=72:00:00
#PBS -N autoencoder_dense
#PBS -A loni_bionoi01
#PBS -j oe

module purge
source activate pytorch
cd ~
cd ../../work/wshi6/deeplearning-data/bionoi_autoencoder_prj/bionoi_autoencoder/
python autoencoder_conv_dense_out_train.py > ./log/autoencoder_conv_dense_out_train.log 2>&1
