#!/bin/bash
#PBS -l nodes=1:ppn=20
#PBS -l walltime=72:00:00
#PBS -q k40
#PBS -N autoencoder_deeper1
#PBS -A loni_bionoi01
#PBS -j oe

source activate pytorch
module purge
cd ~
cd ../../work/wshi6/deeplearning-data/bionoi_autoencoder_prj/bionoi_autoencoder/
python autoencoder_conv_train_deeper1.py > ./log/autoencoder_conv_train_deeper1.log 2>&1